//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class Buff
{
	//public variables

	//private variables
  private bool bActive;
	private GameObject target;

	//public functions
	public Buff (){}

	//Handles checking if the buff is expired.
	public virtual void Update(){
	}

	public virtual void applyBuff(GameObject pTarget){
		//Apply changes to target

	}
	
	//private functions
	public virtual void removeBuff(GameObject pTarget){
		//Revert changes that buff made.
		//Destroy this object
	}

  public bool isActive(){return bActive;}
}
